#!/bin/sh
### BEGIN INIT INFO
# Provides:          endpoint-verification
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Endpoint Verification init script
# Description:       Runs at startup to provide device information to the Google Endpoint Verification native helper
### END INIT INFO

set -e

INSTALL_PREFIX=/opt/google/endpoint-verification
DEVICE_STATE="$INSTALL_PREFIX/bin/device_state.sh"
DEVICE_ATTRS_FILE="$INSTALL_PREFIX/var/lib/device_attrs"

case "$1" in
    start)
      if [ ! -d "$INSTALL_PREFIX" ]; then
        echo "$INSTALL_PREFIX is not available."
        exit 1
      fi

      if [ ! -x "$DEVICE_STATE" ]; then
        echo "$DEVICE_STATE is not available."
        exit 1
      fi

      "$DEVICE_STATE" init >"$DEVICE_ATTRS_FILE"
      ;;
    stop)
      ;;
    restart)
      ;;
esac
